#HTTP Server
server:
  port: 1111

#Discovery Server Access
eureka:
  client:
    service-url:
      default-zone: http://localhost:8766/eureka
  instance:
    status-page-url-path: /infoAlumnos
    health-check-url-path: /healthAlumnos
    metadata-map:
       app-owner: cedser
       description: test application for the expert course